The hate speech and offensive language dataset have been used to view how political polarisation influences the mass population through social media usage. This Twitter dataset contains hate tweets, but we mainly focused on political hate or offensive tweets. 

Installing the necessary packages required for the analysis

In [392]:
pip install nltk


Note: you may need to restart the kernel to use updated packages.


In [393]:
import nltk 


In [394]:
#Importing the necessary libraries

import os
import pandas as pd
import numpy as np
from pprint import pprint

%matplotlib inline


In [395]:
#Loading the data 'Hate Speech and Offensive Language.csv' into a dataframe and viewing its contents
DATAFRAME = pd.read_csv('Hate Speech and Offensive Language.csv' , encoding = "utf8")

DATAFRAME

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [396]:
#Reloading the dataset against to create a list called 'searches' that finds the tweets 
#containing only those words contained in the list. The data is split by "," to separate the columns

with open ('Hate Speech and Offensive Language.csv') as f:
    data = f.read().split(",")

In [397]:
searches = ['Republican', 'democrats', 'Democratic', 'government', 'politics', 'political', 'racism', 'liberal', 'conservative']

for sentence in data:
    if any(i in sentence for i in searches):
        print(sentence)
        

"""@QUAN1T0: 61% of welfare/government aid is claimed by white people. So y'all black slander is trash now."""
219
"""A NO BRAINER""
But as soon as this bitch gets rich in political power
#IndigenousPeoplesDay HAHA!!! You fuckin' retarded commies!!!!! Hunter Biden loves snortin' that PYGMIE FAIRY DUST don't he? #liberals
742
&#8220;@waymoflydenu If you do tax fraud you bet not dare tweet about voting bitch&#8221;all of them tweeting they don't do politics
1988
.@everSoTweetly4u Klain's real (sole) job is to dampen down the mushrooming bad PR and political fallout heading into Nov election.
2236
@1Oyster1 maybe not but you crow about obama and democrats so you are a mawbar....Might as well be a Republican.
2360
 the politically correct term would be ""intellectually disabled."" It's highly offensive to use the word retarded."
2504
@BarneyFranken @jennykutner @Salon salon is is chuck full of butthurt liberal retards
2619
"@BlackManUSA You're killin' me man! &lt;3 Not all conservatives ar

We used the Sentiment dataset to analyze if politics polarise people as the Hate speech and offensive language dataset had an insufficient amount of information to profoundly study and implement for our research work. 

In [398]:
#Loading the Sentiment data into a dataframe
dataframe = pd.read_csv('Sentiment-csv.csv' , encoding = "utf8")

dataframe

candidate  candidate_confidence relevant_yn  \
0      No candidate mentioned                1.0000         yes   
1                Scott Walker                1.0000         yes   
2      No candidate mentioned                1.0000         yes   
3      No candidate mentioned                1.0000         yes   
4                Donald Trump                1.0000         yes   
...                       ...                   ...         ...   
13866  No candidate mentioned                1.0000         yes   
13867           Mike Huckabee                0.9611         yes   
13868                Ted Cruz                1.0000         yes   
13869            Donald Trump                1.0000         yes   
13870                Ted Cruz                0.9242         yes   

       relevant_yn_confidence sentiment  sentiment_confidence  \
0                      1.0000   Neutral                0.6578   
1                      1.0000  Positive                0.6333   
2                      1.0000   Neutral                0.6629   
3                      1.0000  Positive                1.0000   
4                      1.0000  Positive                0.7045   
...                       ...       ...                   ...   
13866                  1.0000  Negative                0.7991   
13867                  1.0000  Positive                0.7302   
13868                  1.0000  Positive                0.8051   
13869                  1.0000  Negative                1.0000   
13870                  0.9614  Positive                0.9614   

                             subject_matter  subject_matter_confidence  \
0                         None of the above                     1.0000   
1                         None of the above                     1.0000   
2                         None of the above                     0.6629   
3                         None of the above                     0.7039   
4                         None of the above                     1.0000   
...                                     ...                        ...   
13866                              Abortion                     0.6014   
13867                     None of the above                     0.9229   
13868                     None of the above                     0.9647   
13869  Women's Issues (not abortion though)                     0.9202   
13870                     None of the above                     0.9242   

               candidate_gold             name relevant_yn_gold  \
0                           0       I_Am_Kenzi                0   
1                           0    PeacefulQuest                0   
2                           0    PussssyCroook                0   
3                           0  MattFromTexas31                0   
4                           0       sharonDay5                0   
...                       ...              ...              ...   
13866  No candidate mentioned    SantoliDonato              yes   
13867           Mike Huckabee         mhfa16hq              yes   
13868                Ted Cruz           DrottM              yes   
13869            Donald Trump     danijeantheq              yes   
13870                Ted Cruz    MichaelHuff52              yes   

       retweet_count     sentiment_gold  \
0                  5                  0   
1                 26                  0   
2                 27                  0   
3                138                  0   
4                156                  0   
...              ...                ...   
13866              7           Negative   
13867              1                  0   
13868             67  Positive\nNeutral   
13869            149                  0   
13870             65           Positive   

                                  subject_matter_gold  \
0                                                 NaN   
1                                                 NaN   
2                                                 Na

In [399]:
#Exploring the columns
dataframe.columns

Index(['candidate', 'candidate_confidence', 'relevant_yn',
       'relevant_yn_confidence', 'sentiment', 'sentiment_confidence',
       'subject_matter', 'subject_matter_confidence', 'candidate_gold', 'name',
       'relevant_yn_gold', 'retweet_count', 'sentiment_gold',
       'subject_matter_gold', 'text', 'tweet_coord', 'tweet_created',
       'tweet_id', 'tweet_location', 'user_timezone'],
      dtype='object')

In [400]:
#Dropping the columns that are not useful to train our machine learning models
dataframe.drop([ 'candidate', 'candidate_confidence', 'relevant_yn',
       'relevant_yn_confidence','sentiment_confidence',
       'subject_matter_confidence', 'candidate_gold', 'name',
       'relevant_yn_gold','sentiment_gold',
       'subject_matter_gold','tweet_coord', 'tweet_created',
       'tweet_id', 'tweet_location', 'user_timezone'], axis = 1, inplace = True) 
dataframe

sentiment                        subject_matter  retweet_count  \
0       Neutral                     None of the above              5   
1      Positive                     None of the above             26   
2       Neutral                     None of the above             27   
3      Positive                     None of the above            138   
4      Positive                     None of the above            156   
...         ...                                   ...            ...   
13866  Negative                              Abortion              7   
13867  Positive                     None of the above              1   
13868  Positive                     None of the above             67   
13869  Negative  Women's Issues (not abortion though)            149   
13870  Positive                     None of the above             65   

                                                    text  
0      RT @NancyLeeGrahn: How did everyone feel about...  
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  
2      RT @TJMShow: No mention of Tamir Rice and the ...  
3      RT @RobGeorge: That Carly Fiorina is trending ...  
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  
...                                                  ...  
13866  RT @cappy_yarbrough: Love to see men who will ...  
13867  RT @georgehenryw: Who thought Huckabee exceede...  
13868  RT @Lrihendry: #TedCruz As President, I will a...  
13869  RT @JRehling: #GOPDebate Donald Trump says tha...  
13870  RT @Lrihendry: #TedCruz headed into the Presid...  

[13871 rows x 4 columns]

In [401]:
#Now we convert the dataframe into a csv file 
FILE = dataframe.to_csv(r'../AI2/updated_data.csv', index = False)

In [402]:
#We load the dataset "updated_data.csv" here 
df = pd.read_csv('updated_data.csv' , encoding = "utf8")

#We convert the columns 'text', 'subject_matter' to float and store it in new columns as this will help us 
# to build the train-test split and also train these columns.

# Importing label encoder 
from sklearn import preprocessing 

# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

# Encode labels in column. 
df['text_Float']= label_encoder.fit_transform(df['text']) 
df['subject_matter_Float']= label_encoder.fit_transform(df['subject_matter']) 

df['text_Float'].unique() 


array([5898, 6307, 6485, ..., 8485, 3940, 9458])

In [403]:
df.head()

sentiment     subject_matter  retweet_count  \
0   Neutral  None of the above              5   
1  Positive  None of the above             26   
2   Neutral  None of the above             27   
3  Positive  None of the above            138   
4  Positive  None of the above            156   

                                                text  text_Float  \
0  RT @NancyLeeGrahn: How did everyone feel about...        5898   
1  RT @ScottWalker: Didn't catch the full #GOPdeb...        6307   
2  RT @TJMShow: No mention of Tamir Rice and the ...        6485   
3  RT @RobGeorge: That Carly Fiorina is trending ...        6225   
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...        4936   

   subject_matter_Float  
0                     9  
1                     9  
2                     9  
3                     9  
4                     9

In [404]:
#Checking for null values
df.isnull().sum()

sentiment               0
subject_matter          0
retweet_count           0
text                    0
text_Float              0
subject_matter_Float    0
dtype: int64

In [405]:
#Exploring the subject matters
df["subject_matter"].value_counts()


None of the above                       8148
FOX News or Moderators                  2900
Religion                                 407
Foreign Policy                           366
Women's Issues (not abortion though)     362
Racial issues                            353
0                                        326
Abortion                                 293
Jobs and Economy                         251
Immigration                              211
LGBT issues                              126
Healthcare (including Medicare)           67
Gun Control                               61
Name: subject_matter, dtype: int64

In [406]:
#Converting columns to series
df.columns = df.columns.to_series().apply(lambda x: x.strip())


In [407]:
#Before we instantiate our ML model, we divide the dataset into two smaller training and testing datasets.
#We also set up our Features (X) and Labels (y) where X is 'text_Float','subject_matter_Float', and 'retweet_count'.
#y is 'sentiment'

#Importing train_test_split
from sklearn.model_selection import train_test_split

# test size represents the proportion of training and testing data split. 
X = df[['text_Float','subject_matter_Float', 'retweet_count']]
y = df['sentiment']

#Random_state is set to 1 to define the "randomness" of data randomisation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [408]:
X_train.shape

(11096, 3)

In [409]:
#Examining the size of the training and testing datasets.
print('X training data shape', X_train.shape)
print('X testing data shape', X_test.shape)

X training data shape (11096, 3)
X testing data shape (2775, 3)


In [410]:
# Showing column of label data
print('y training data shape', y_train.shape)
print('y testing data shape', y_test.shape)

y training data shape (11096,)
y testing data shape (2775,)


In [411]:
y_train

2195      Neutral
6268      Neutral
8799     Negative
12454    Positive
13455    Negative
           ...   
905      Negative
5192     Negative
12172    Negative
235      Negative
13349    Negative
Name: sentiment, Length: 11096, dtype: object

In [412]:
print(X_test)

       text_Float  subject_matter_Float  retweet_count
3589         1251                     9              0
3660          955                     9              1
9068         5002                     9             66
9153         6126                     2            142
11875         234                     9              0
...           ...                   ...            ...
231          6637                     3              9
3132         7748                     9              1
3499          712                     9              1
13495        7597                     9              2
7593         7566                     9             26

[2775 rows x 3 columns]


In [413]:
X_train

text_Float  subject_matter_Float  retweet_count
2195         2917                     9             38
6268         7890                     9            137
8799         6111                     2             64
12454        6122                     2             71
13455        7742                     9              9
...           ...                   ...            ...
905          3934                     9              0
5192         9213                    11              0
12172         576                     9              0
235          1091                     2              0
13349        9754                     7              1

[11096 rows x 3 columns]

In [414]:
#import LogisticRegression from sklearn
from sklearn.linear_model import LogisticRegression
#We build the model with the L-BFGS option.
#Once the model is built, the training data is then provided to the model.


log_reg_model = LogisticRegression(solver = "lbfgs")

log_reg_model.fit(X_train, y_train)

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [415]:
#We test the accuracy of the model using the test data.
#We import the sklearn.metrics module which includes score functions, performance metrics and pairwise metrics and distance computations. 
#We create a predictions set with some test data. This is unseen data

from sklearn import metrics

# Creating a prediction set here
# Unseen contents of X_test
log_regression_model_predictions = log_reg_model.predict(X_test)

In [416]:
# This is the predicted output from the model
log_regression_model_predictions

array(['Negative', 'Negative', 'Negative', ..., 'Negative', 'Negative',
       'Negative'], dtype=object)

In [417]:
# Now we compare what the model predicted 
# with what is expected as output
# Printing a confusion matrix
print(metrics.confusion_matrix(y_test,log_regression_model_predictions))


[[1714    5    0]
 [ 618    2    0]
 [ 436    0    0]]


In [418]:
# Printing a classification report
print(metrics.classification_report(y_test,log_regression_model_predictions))

              precision    recall  f1-score   support

    Negative       0.62      1.00      0.76      1719
     Neutral       0.29      0.00      0.01       620
    Positive       0.00      0.00      0.00       436

    accuracy                           0.62      2775
   macro avg       0.30      0.33      0.26      2775
weighted avg       0.45      0.62      0.47      2775



C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [419]:
# Printing the overall accuracy
print(metrics.accuracy_score(y_test,log_regression_model_predictions))

0.6183783783783784


In [420]:
# Import  MultinomialNB from sklearn
from sklearn.naive_bayes import MultinomialNB

# An instance of the model is created
Mnb_model = MultinomialNB()

# Fitting model to the training data
Mnb_model.fit(X_train, y_train)

MultinomialNB()

In [421]:
# Predict answers to data from the X_text dataset and show results in a confusion matrix
Mnb_model_predictions = Mnb_model.predict(X_test)

print(metrics.confusion_matrix(y_test,Mnb_model_predictions))

[[ 454 1265    0]
 [ 128  492    0]
 [ 126  310    0]]


In [422]:
#printing the classification report and the accuracy
print(metrics.classification_report(y_test,Mnb_model_predictions))


              precision    recall  f1-score   support

    Negative       0.64      0.26      0.37      1719
     Neutral       0.24      0.79      0.37       620
    Positive       0.00      0.00      0.00       436

    accuracy                           0.34      2775
   macro avg       0.29      0.35      0.25      2775
weighted avg       0.45      0.34      0.31      2775



C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [423]:
print(metrics.accuracy_score(y_test,Mnb_model_predictions))

0.3409009009009009


In [424]:
# Import RandomForestClassifier from sklearn
from sklearn.ensemble import RandomForestClassifier

# An instance of the RF model is created
RF_model = RandomForestClassifier()

# Fitting the model to the training data
RF_model.fit(X_train, y_train)

RandomForestClassifier()

In [425]:
# Predict answers to data from the X_text dataset and show results in a confusion matrix
RF_model_predictions = RF_model.predict(X_test)

print(metrics.confusion_matrix(y_test,RF_model_predictions))

[[1222  319  178]
 [ 356  175   89]
 [ 198   84  154]]


In [426]:
#Printing the classification report and accuracy
print(metrics.classification_report(y_test,RF_model_predictions))


              precision    recall  f1-score   support

    Negative       0.69      0.71      0.70      1719
     Neutral       0.30      0.28      0.29       620
    Positive       0.37      0.35      0.36       436

    accuracy                           0.56      2775
   macro avg       0.45      0.45      0.45      2775
weighted avg       0.55      0.56      0.55      2775



In [427]:
print(metrics.accuracy_score(y_test,RF_model_predictions))


0.5589189189189189


In [428]:
# Importing a Support Vector Classification model (SVC)
from sklearn.svm import SVC

# The gamma value is set to "auto" to avoid returning error. We fit the SVC model on our data. The confusion matrix is printed.
SVCmodel = SVC(gamma="auto")
SVCmodel.fit(X_train, y_train)

SVCmodel_predictions = SVCmodel.predict(X_test)

print(metrics.confusion_matrix(y_test, SVCmodel_predictions))

[[1587   99   33]
 [ 506   87   27]
 [ 299   33  104]]


In [429]:
#Printing the classification report and accuracy
print(metrics.classification_report(y_test,SVCmodel_predictions))


              precision    recall  f1-score   support

    Negative       0.66      0.92      0.77      1719
     Neutral       0.40      0.14      0.21       620
    Positive       0.63      0.24      0.35       436

    accuracy                           0.64      2775
   macro avg       0.56      0.43      0.44      2775
weighted avg       0.60      0.64      0.58      2775



In [430]:
print(metrics.accuracy_score(y_test,SVCmodel_predictions))


0.6407207207207207


Reference:
    Dr. James Connolly's Supervised learning practical notes from AI2.