Analysing hate crime in Europe to identify the hate bias and the targeted groups 

In [163]:
#Importing the necessary libraries here
import os
import pandas as pd
import numpy as np
from pprint import pprint

%matplotlib inline

In [164]:
#Loading the dataset 'cases-and-rulings-full.csv' into a dataframe
dataframe = pd.read_csv('cases-and-rulings-full.csv' , encoding = "utf8")

dataframe

Country  Year                                     Case reference  \
0          Slovenia  2019  Slovenia / Supreme Court / Order X Ips 21/2019...   
1    United Kingdom  2019  United Kingdom / Her Majesty's Attorney Genera...   
2            Cyprus  2019  Cyprus/ District Court of Nicosia/ Case No. 77...   
3          Slovakia  2019  Slovakia / Specialized Criminal Court / 2T/15/...   
4         Lithuania  2019  Lithuania / Supreme administrative court of Li...   
..              ...   ...                                                ...   
262         Denmark  2012  UN, International Convention onthe Elimination...   
263           Italy  2012  Italy / Ordinary Court of Padua / Decision no....   
264           Spain  2012          Spain / Vigo Criminal Court / No. 22/2012   
265           Spain  2019  Spain / Madrid Provincial High Court , Crimina...   
266         Austria  2016    Austria / Regional Court Vienna / 112 Hv 66/16w   

                                                   URL  \
0    http://www.sodnapraksa.si/search.php?q=Sklep%2...   
1    https://www.bailii.org/ew/cases/EWHC/QB/2019/1...   
2    http://www.cylaw.org/cgi-bin/open.pl?file=apof...   
3    https://obcan.justice.sk/infosud/-/infosud/i-d...   
4    https://eteismai.lt/byla/245652486312128/A-185...   
..                                                 ...   
262  http://www2.ohchr.org/english/bodies/cerd/docs...   
263  http://old.asgi.it/public/parser_download/save...   
264  https://www.iberley.es/jurisprudencia/sentenci...   
265  http://www.poderjudicial.es/search/openDocumen...   
266                                                NaN   

    Decision / ruling / judgment Date  \
0                     Tue, 08/13/2019   
1                     Tue, 07/09/2019   
2                     Mon, 07/01/2019   
3                     Wed, 06/26/2019   
4                     Wed, 06/19/2019   
..                                ...   
262                   Tue, 03/06/2012   
263                   Tue, 02/07/2012   
264                   Tue, 01/24/2012   
265                   Thu, 01/01/1970   
266                               NaN   

                                         Crime type(s)  \
0                                          Hate speech   
1                                          Hate speech   
2                                          Hate speech   
3    Incitement to violence or hatred, Threat of vi...   
4                                       Discrimination   
..                                                 ...   
262       Physical violence, Vandalism, Discrimination   
263                   Incitement to violence or hatred   
264                   Incitement to violence or hatred   
265                                        Hate speech   
266                   Incitement to violence or hatred   

                         HATE BIAS  \
0                   Migrant status   
1                         Religion   
2                             Race   
3    Race, Ethnic origin, Religion   
4                         Religion   
..                             ...   
262                  Ethnic origin   
263                           Race   
264                  Ethnic origin   
265                       Religion   
266                    Nationality   

                                                GROUPS      Court / Body type  \
0                                             Migrants  National Higher Court   
1                                              Muslims  National Higher Court   
2                                             Migrants         National court   
3    Muslims, Black people or of African origin, Ot...         National court   
4                                              Muslims  National Higher Court   
..                                                 ...                    ...   
262                          Refugees & Asylum seekers      UN CERD Committee   
263                            Third country nationals     

In [165]:
#Checking for null values
dataframe.isnull().sum()

Country                                                                                                                       0
Year                                                                                                                          0
Case reference                                                                                                                0
URL                                                                                                                          66
Decision / ruling / judgment Date                                                                                             1
Crime type(s)                                                                                                                 0
HATE BIAS                                                                                                                     0
GROUPS                                                                                                  

In [166]:
#Exploring the columns
dataframe.columns

Index(['Country', 'Year', 'Case reference', 'URL',
       'Decision / ruling / judgment Date', 'Crime type(s)', 'HATE BIAS',
       'GROUPS', 'Court / Body type', 'Court / Body', 'KEY FACTS',
       'Main reasoning / argumentation',
       'Is the case related to the application of the Framework Decision on Racism and Xenophobia, the Racial Equality Directive?',
       'Key issues (concepts, interpretations) clarified by the case',
       'Results (sanctions, outcome) and key consequences or implications of the case',
       'Key quotation in original language and translated into English  with reference details'],
      dtype='object')

In [167]:
#Dropping the columns that are not useful to train our machine learning models

dataframe.drop(['Case reference', 'URL','Decision / ruling / judgment Date', 'Court / Body type', 'Court / Body', 'KEY FACTS',
       'Main reasoning / argumentation','Key issues (concepts, interpretations) clarified by the case',
       'Results (sanctions, outcome) and key consequences or implications of the case',
       'Key quotation in original language and translated into English  with reference details'], axis = 1, inplace = True)
dataframe



Country  Year                                      Crime type(s)  \
0          Slovenia  2019                                        Hate speech   
1    United Kingdom  2019                                        Hate speech   
2            Cyprus  2019                                        Hate speech   
3          Slovakia  2019  Incitement to violence or hatred, Threat of vi...   
4         Lithuania  2019                                     Discrimination   
..              ...   ...                                                ...   
262         Denmark  2012       Physical violence, Vandalism, Discrimination   
263           Italy  2012                   Incitement to violence or hatred   
264           Spain  2012                   Incitement to violence or hatred   
265           Spain  2019                                        Hate speech   
266         Austria  2016                   Incitement to violence or hatred   

                         HATE BIAS  \
0                   Migrant status   
1                         Religion   
2                             Race   
3    Race, Ethnic origin, Religion   
4                         Religion   
..                             ...   
262                  Ethnic origin   
263                           Race   
264                  Ethnic origin   
265                       Religion   
266                    Nationality   

                                                GROUPS  \
0                                             Migrants   
1                                              Muslims   
2                                             Migrants   
3    Muslims, Black people or of African origin, Ot...   
4                                              Muslims   
..                                                 ...   
262                          Refugees & Asylum seekers   
263                            Third country nationals   
264  Muslims, Migrants, Refugees & Asylum seekers, ...   
265                                            Muslims   
266                          Refugees & Asylum seekers   

    Is the case related to the application of the Framework Decision on Racism and Xenophobia, the Racial Equality Directive?  
0                                                No.\n                                                                         
1                                                N/A\n                                                                         
2    No. The charge and therefore the Court decisio...                                                                         
3                                                No.\n                                                                         
4                                                No.\n                                                                         
..                                                 ...                                                                         
262                                                NaN                                                                         
263                                   No, it is not.\n                                                                         
264  Yes,  The case is related to the Framework Dec...                                                                         
265  The case is related to the Framework Decision ...                                                                         
266                           Not publicly available\n                                                                         

[267 rows x 6 columns]

In [168]:
#Exploring the list of countries
dataframe.Country.unique()

array(['Slovenia', 'United Kingdom', 'Cyprus', 'Slovakia', 'Lithuania',
       'Malta', 'Belgium', 'Germany', 'Netherlands', 'Greece',
       'Luxembourg', 'Finland', 'Spain', 'Austria', 'Hungary', 'France',
       'Serbia', 'North Macedonia', 'Denmark', 'Sweden', 'Poland',
       'Croatia', 'Italy', 'Portugal', 'Bulgaria', 'Romania', 'Estonia',
       'Latvia', 'Czechia', 'Ireland'], dtype=object)

In [169]:
from sklearn import preprocessing 

# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

# Encoding the labels in column. 
dataframe['country_encoded']= label_encoder.fit_transform(dataframe['Country']) 
dataframe['crimes_encoded'] = label_encoder.fit_transform(dataframe['Crime type(s)'])
dataframe['bias groups']= label_encoder.fit_transform(dataframe['GROUPS']) 
dataframe['hate_bias']= label_encoder.fit_transform(dataframe['HATE BIAS']) 

dataframe.head(10)

Country  Year                                      Crime type(s)  \
0        Slovenia  2019                                        Hate speech   
1  United Kingdom  2019                                        Hate speech   
2          Cyprus  2019                                        Hate speech   
3        Slovakia  2019  Incitement to violence or hatred, Threat of vi...   
4       Lithuania  2019                                     Discrimination   
5           Malta  2019  Physical violence, Incitement to violence or h...   
6         Belgium  2019  Incitement to violence or hatred, Harassment, ...   
7  United Kingdom  2019                   Incitement to violence or hatred   
8         Germany  2019                   Incitement to violence or hatred   
9     Netherlands  2019                                        Hate speech   

                         HATE BIAS  \
0                   Migrant status   
1                         Religion   
2                             Race   
3    Race, Ethnic origin, Religion   
4                         Religion   
5                             Race   
6  Ethnic origin, Gender, Religion   
7   Race, Religion, Migrant status   
8                         Religion   
9              Race, Ethnic origin   

                                              GROUPS  \
0                                           Migrants   
1                                            Muslims   
2                                           Migrants   
3  Muslims, Black people or of African origin, Ot...   
4                                            Muslims   
5                  Black people or of African origin   
6  Muslims, EU citizens & nationals with migrant ...   
7  Muslims, Migrants, Refugees & Asylum seekers, ...   
8                                            Muslims   
9                  Black people or of African origin   

  Is the case related to the application of the Framework Decision on Racism and Xenophobia, the Racial Equality Directive?  \
0                                              No.\n                                                                          
1                                              N/A\n                                                                          
2  No. The charge and therefore the Court decisio...                                                                          
3                                              No.\n                                                                          
4                                              No.\n                                                                          
5  Yes.The provisions applied were added to the C...                                                                          
6  Yes. The Court refers to the Law of 30 July 19...                                                                          
7  Yes – the case is related to the application o...                                                                          
8                                              No.\n                                                                          
9  Articles 137c en 137d of the Dutch criminal co...                                                                          

   country_encoded  crimes_encoded  bias groups  hate_bias  
0               26               5            8         10  
1               29               5           14         31  
2                4               5            8         20  
3               25              15           15         24  
4               16               1           14         31  
5               18              19            0         20  
6                1              12           16          2  
7               29               9           22         30  
8               10               9           14         31  
9               19               5            0         21

In [170]:
#Before we instantiate our ML model, we divide the dataset into two smaller training and testing datasets.
#We also set up our Features (X) and Labels (y) where X is 'country_encoded', 'crimes_encoded', and 'bias groups'.
#y is 'HATE BIAS'

from sklearn.model_selection import train_test_split

# test size represents the proportion of training and testing data split. 
X = dataframe[['country_encoded', 'crimes_encoded', 'bias groups']]
Y = dataframe['HATE BIAS']

#Random_state is set to 1 to define the "randomness" of data randomisation
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [171]:
# Importing  MultinomialNB from sklearn
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


# Creating an instance of the model
NB_model = MultinomialNB()

# Fitting the model to training data
NB_model.fit(X_train, Y_train)

MultinomialNB()

In [172]:
# Predicting answers to data from the X_text dataset
NB_model_predictions = NB_model.predict(X_test)

# Showing the results in a confusion matrix
print(metrics.confusion_matrix(Y_test,NB_model_predictions))

[[0 1 1 0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 2 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 2 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0]
 [2 0 1 0 3 0 0 1 0 0 2 0 0 0 0 9 0 0 0 4]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [173]:
#Printing the classification report and the accuracy
print(metrics.classification_report(Y_test,NB_model_predictions))


                                            precision    recall  f1-score   support

                             Ethnic origin       0.00      0.00      0.00         6
                     Ethnic origin, Gender       0.00      0.00      0.00         0
                       Ethnic origin, Race       0.00      0.00      0.00         0
Ethnic origin, Race, Nationality, Religion       0.00      0.00      0.00         0
                   Ethnic origin, Religion       0.00      0.00      0.00         1
                            Migrant status       0.33      0.50      0.40         2
                  Migrant status, Religion       0.00      0.00      0.00         1
                               Nationality       0.33      0.17      0.22         6
                Nationality, Ethnic origin       0.00      0.00      0.00         2
               Nationality, Migrant status       0.00      0.00      0.00         1
                         Nationality, Race       0.00      0.00      0.00  

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [174]:
print(metrics.accuracy_score(Y_test,NB_model_predictions))

0.2222222222222222


In [175]:
#Importing the Random Forest Classifier model
from sklearn.ensemble import RandomForestClassifier

# Creating an instance of the model
rf_model = RandomForestClassifier()

# Fitting the model on training data
rf_model.fit(X_train, Y_train)

RandomForestClassifier()

In [176]:
# Predicting the answers to data from the X_text dataset
rf_model_predictions = rf_model.predict(X_test)

# Printing the confusion matrix
print(metrics.confusion_matrix(Y_test,rf_model_predictions))

[[ 3  0  0  0  0  0  0  0  0  0  1  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  3  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  1  1  0  0  1  0  1  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  2  0  0  1  0  0  0 18  0  0  0]
 [ 1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0

In [177]:
#Printing the classification report and the accuracy
print(metrics.classification_report(Y_test,rf_model_predictions))


                                      precision    recall  f1-score   support

                       Ethnic origin       0.50      0.50      0.50         6
       Ethnic origin, Migrant status       0.00      0.00      0.00         0
                 Ethnic origin, Race       0.00      0.00      0.00         0
             Ethnic origin, Religion       0.00      0.00      0.00         1
Ethnic origin, Religion, Nationality       0.00      0.00      0.00         0
                      Migrant status       0.40      1.00      0.57         2
            Migrant status, Religion       0.00      0.00      0.00         1
                         Nationality       0.50      0.50      0.50         6
          Nationality, Ethnic origin       0.00      0.00      0.00         2
         Nationality, Migrant status       0.00      0.00      0.00         1
                                Race       0.20      0.20      0.20         5
                 Race, Ethnic origin       0.00      0.00      

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [178]:
print(metrics.accuracy_score(Y_test,rf_model_predictions))


0.5370370370370371


In [179]:
# Importing the Support Vector Classification model (SVC)
from sklearn.svm import SVC

# The gamma value is set to "auto" to avoid returning error. We fit the SVC model on our data. The confusion matrix is printed.
svc_model = SVC(gamma="auto")
svc_model.fit(X_train, Y_train)

svc_model_predictions = svc_model.predict(X_test)

print(metrics.confusion_matrix(Y_test, svc_model_predictions))

[[ 0  0  0  0  0  0  0  0  1  0  5  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0 20  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]]


In [180]:
print(metrics.classification_report(Y_test,svc_model_predictions))

                                  precision    recall  f1-score   support

                   Ethnic origin       0.00      0.00      0.00         6
         Ethnic origin, Religion       0.00      0.00      0.00         1
                  Migrant status       0.00      0.00      0.00         2
        Migrant status, Religion       0.00      0.00      0.00         1
                     Nationality       0.57      0.67      0.62         6
      Nationality, Ethnic origin       0.00      0.00      0.00         2
     Nationality, Migrant status       0.00      0.00      0.00         1
                            Race       0.00      0.00      0.00         5
             Race, Ethnic origin       0.00      0.00      0.00         1
Race, Nationality, Ethnic origin       0.00      0.00      0.00         2
                        Religion       0.48      0.91      0.62        22
         Religion, Ethnic origin       0.00      0.00      0.00         2
                Religion, Gender     

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [181]:
print(metrics.accuracy_score(Y_test,svc_model_predictions))


0.4444444444444444


In [182]:
#We import LogisticRegression from sklearn
from sklearn.linear_model import LogisticRegression
#We build the model with the L-BFGS option.
#Once the model is built, the training data is then provided to the model.

log_reg_model = LogisticRegression(solver = "lbfgs")

log_reg_model.fit(X_train, Y_train)

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [183]:
#We test the accuracy of the model using the test data.
#We import the sklearn.metrics module which includes score functions, performance metrics and pairwise metrics and distance computations. 
#We create a predictions set with some test data. This is unseen data. 

from  sklearn import metrics

# Creating a prediction set here
# Unseen contents of X_test
log_reg_model_predictions = log_reg_model.predict(X_test)

In [184]:
# This is the predicted output from the model
log_reg_model_predictions

array(['Religion', 'Religion', 'Religion', 'Religion', 'Religion',
       'Religion', 'Migrant status', 'Religion', 'Ethnic origin', 'Race',
       'Ethnic origin', 'Ethnic origin', 'Religion', 'Religion',
       'Religion', 'Religion', 'Ethnic origin', 'Religion',
       'Ethnic origin', 'Religion', 'Religion', 'Religion',
       'Ethnic origin', 'Religion', 'Religion', 'Religion', 'Religion',
       'Religion', 'Religion', 'Religion', 'Religion', 'Religion', 'Race',
       'Religion', 'Religion', 'Religion', 'Religion', 'Ethnic origin',
       'Religion', 'Religion', 'Religion', 'Religion', 'Religion',
       'Religion', 'Religion', 'Religion', 'Race', 'Religion', 'Religion',
       'Religion', 'Religion', 'Religion', 'Religion', 'Migrant status'],
      dtype=object)

In [185]:
#Printing the confusion matrix, classification report and accuracy
print(metrics.confusion_matrix(Y_test,log_reg_model_predictions))

[[ 2  0  0  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]]


In [186]:
print(metrics.classification_report(Y_test,log_reg_model_predictions))

                                  precision    recall  f1-score   support

                   Ethnic origin       0.29      0.33      0.31         6
         Ethnic origin, Religion       0.00      0.00      0.00         1
                  Migrant status       0.50      0.50      0.50         2
        Migrant status, Religion       0.00      0.00      0.00         1
                     Nationality       0.00      0.00      0.00         6
      Nationality, Ethnic origin       0.00      0.00      0.00         2
     Nationality, Migrant status       0.00      0.00      0.00         1
                            Race       0.33      0.20      0.25         5
             Race, Ethnic origin       0.00      0.00      0.00         1
Race, Nationality, Ethnic origin       0.00      0.00      0.00         2
                        Religion       0.52      1.00      0.69        22
         Religion, Ethnic origin       0.00      0.00      0.00         2
                Religion, Gender     

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [187]:
print(metrics.accuracy_score(Y_test,log_reg_model_predictions))

0.48148148148148145


In [188]:
#Before we instantiate our ML model, we divide the dataset into two smaller training and testing datasets.
#We also set up our Features (X) and Labels (y) where X is 'country_encoded', 'crimes_encoded', 'hate_bias'.
#y is 'GROUPS'
from sklearn.model_selection import train_test_split

# test size represents the proportion of training and testing data split. 
X = dataframe[['country_encoded', 'crimes_encoded', 'hate_bias']]
y = dataframe['GROUPS']

# Random_state sets "randomness" of data randomisation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [189]:
#Importing the random forest classification model
from sklearn.ensemble import RandomForestClassifier

# Create an instance of the model
RF_model = RandomForestClassifier()

# Fit model to training data
RF_model.fit(X_train, y_train)

RandomForestClassifier()

In [190]:
# Predicting answers to data from the X_text dataset
RF_model_predictions = RF_model.predict(X_test)

# Showing results in a confusion matrix
print(metrics.confusion_matrix(y_test,RF_model_predictions))

[[ 1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  1  0  0]
 [ 1  0  0  0  3  1  0  0  0  0  0  0  0  0  3  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  4  0  1]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]]


In [191]:
#Printing the classification report and the accuracy
print(metrics.classification_report(y_test,RF_model_predictions))


                                                                                                                                                                                               precision    recall  f1-score   support

                                                                                                                                                            Black people or of African origin       0.50      0.50      0.50         2
                                                                                                                                              EU citizens & nationals with migrant background       0.00      0.00      0.00         1
                                                                                                                                                                                   Foreigners       0.00      0.00      0.00         1
                                                                           

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [192]:
print(metrics.accuracy_score(y_test,RF_model_predictions))


0.5370370370370371


Reference:
    Dr. James Connolly's Supervised learning practical notes from AI2.