To identify the causes behind shooting-based hate crimes we perform this data analysis.

In [1]:
#Importing necessary libraries here
import os
import pandas as pd
import numpy as np
from pprint import pprint

%matplotlib inline

In [2]:
#Loading the dataset into a dataframe
dataframe = pd.read_csv('hate_crime-csv.csv' , encoding = "utf8")

dataframe

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


INCIDENT_ID  DATA_YEAR        ORI PUB_AGENCY_NAME PUB_AGENCY_UNIT  \
0              3015       1991  AR0040200          Rogers             NaN   
1              3016       1991  AR0290100            Hope             NaN   
2                43       1991  AR0350100      Pine Bluff             NaN   
3                44       1991  AR0350100      Pine Bluff             NaN   
4              3017       1991  AR0350100      Pine Bluff             NaN   
...             ...        ...        ...             ...             ...   
201398       466130       2018  WV0540100     Parkersburg             NaN   
201399       466159       2018  WV0540100     Parkersburg             NaN   
201400       508677       2018  WV0540200          Vienna             NaN   
201401       463503       2018  WVWSP2400   State Police:         Madison   
201402       544359       2018  WVWSP3300   State Police:     Parkersburg   

       AGENCY_TYPE_NAME STATE_ABBR     STATE_NAME       DIVISION_NAME  \
0                  City         AR       Arkansas  West South Central   
1                  City         AR       Arkansas  West South Central   
2                  City         AR       Arkansas  West South Central   
3                  City         AR       Arkansas  West South Central   
4                  City         AR       Arkansas  West South Central   
...                 ...        ...            ...                 ...   
201398             City         WV  West Virginia      South Atlantic   
201399             City         WV  West Virginia      South Atlantic   
201400             City         WV  West Virginia      South Atlantic   
201401     State Police         WV  West Virginia      South Atlantic   
201402     State Police         WV  West Virginia      South Atlantic   

       REGION_NAME  ...              OFFENDER_RACE OFFENDER_ETHNICITY  \
0            South  ...                      White                NaN   
1            South  ...  Black or African American                NaN   
2            South  ...  Black or African American                NaN   
3            South  ...  Black or African American                NaN   
4            South  ...  Black or African American                NaN   
...            ...  ...                        ...                ...   
201398       South  ...                    Unknown            Unknown   
201399       South  ...                      White            Unknown   
201400       South  ...                    Unknown            Unknown   
201401       South  ...                      White            Unknown   
201402       South  ...                    Unknown            Unknown   

       VICTIM_COUNT                                       OFFENSE_NAME  \
0                 1                                       Intimidation   
1                 1                                     Simple Assault   
2                 1                                 Aggravated Assault   
3                 2  Aggravated Assault;Destruction/Damage/Vandalis...   
4                 1                                 Aggravated Assault   
...             ...                                                ...   
201398            1                       Burglary/Breaking & Entering   
201399            1                                     Simple Assault   
201400            1                                       Intimidation   
201401            1                                       Intimidation   
201402            2  Burglary/Breaking & Entering;Destruction/Damag...   

        TOTAL_INDIVIDUAL_VICTIMS                       LOCATION_NAME  \
0                            1.0  Highway/Road/Alley/Street/Sidewalk   
1                            1.0  Highway/Road/Alley/Street/Sidewalk   
2                            1.0                      Residence/Home   
3                            1.0  Highway/Road/Alley/Street/Sidewalk   
4                            1.0                 Service/Gas Station   
...     

In [3]:
#Checking fro null values
dataframe.isnull().sum()

INCIDENT_ID                      0
DATA_YEAR                        0
ORI                              0
PUB_AGENCY_NAME                  0
PUB_AGENCY_UNIT             195809
AGENCY_TYPE_NAME                 0
STATE_ABBR                       0
STATE_NAME                       0
DIVISION_NAME                    0
REGION_NAME                      0
POPULATION_GROUP_CODE            0
POPULATION_GROUP_DESC            0
INCIDENT_DATE                    0
ADULT_VICTIM_COUNT          165430
JUVENILE_VICTIM_COUNT       165907
TOTAL_OFFENDER_COUNT             0
ADULT_OFFENDER_COUNT        167451
JUVENILE_OFFENDER_COUNT     167458
OFFENDER_RACE                    0
OFFENDER_ETHNICITY          183253
VICTIM_COUNT                     0
OFFENSE_NAME                     0
TOTAL_INDIVIDUAL_VICTIMS      1606
LOCATION_NAME                    0
BIAS_DESC                        0
VICTIM_TYPES                     0
MULTIPLE_OFFENSE                 0
MULTIPLE_BIAS                    0
dtype: int64

In [4]:
#Exploring the columns
dataframe.columns

Index(['INCIDENT_ID', 'DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'PUB_AGENCY_UNIT',
       'AGENCY_TYPE_NAME', 'STATE_ABBR', 'STATE_NAME', 'DIVISION_NAME',
       'REGION_NAME', 'POPULATION_GROUP_CODE', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT', 'OFFENDER_RACE', 'OFFENDER_ETHNICITY',
       'VICTIM_COUNT', 'OFFENSE_NAME', 'TOTAL_INDIVIDUAL_VICTIMS',
       'LOCATION_NAME', 'BIAS_DESC', 'VICTIM_TYPES', 'MULTIPLE_OFFENSE',
       'MULTIPLE_BIAS'],
      dtype='object')

In [5]:
#Dropping the columns that are not useful to train our machine learning models
dataframe.drop(['INCIDENT_ID', 'DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'PUB_AGENCY_UNIT',
       'AGENCY_TYPE_NAME', 'STATE_ABBR', 'STATE_NAME', 'DIVISION_NAME',
       'REGION_NAME', 'POPULATION_GROUP_CODE', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT','OFFENDER_ETHNICITY',
       'VICTIM_COUNT', 'TOTAL_INDIVIDUAL_VICTIMS',
       'LOCATION_NAME','MULTIPLE_OFFENSE',
       'MULTIPLE_BIAS'], axis = 1, inplace = True)
dataframe



OFFENDER_RACE  \
0                           White   
1       Black or African American   
2       Black or African American   
3       Black or African American   
4       Black or African American   
...                           ...   
201398                    Unknown   
201399                      White   
201400                    Unknown   
201401                      White   
201402                    Unknown   

                                             OFFENSE_NAME  \
0                                            Intimidation   
1                                          Simple Assault   
2                                      Aggravated Assault   
3       Aggravated Assault;Destruction/Damage/Vandalis...   
4                                      Aggravated Assault   
...                                                   ...   
201398                       Burglary/Breaking & Entering   
201399                                     Simple Assault   
201400                                       Intimidation   
201401                                       Intimidation   
201402  Burglary/Breaking & Entering;Destruction/Damag...   

                             BIAS_DESC             VICTIM_TYPES  
0       Anti-Black or African American               Individual  
1                           Anti-White               Individual  
2       Anti-Black or African American               Individual  
3                           Anti-White               Individual  
4                           Anti-White               Individual  
...                                ...                      ...  
201398  Anti-Black or African American               Individual  
201399  Anti-Black or African American               Individual  
201400                      Anti-Asian               Individual  
201401                      Anti-White  Law Enforcement Officer  
201402             Anti-Other Religion   Religious Organization  

[201403 rows x 4 columns]

In [6]:
from sklearn import preprocessing 

# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

# Encode labels in column. 
dataframe['offense_encoded']= label_encoder.fit_transform(dataframe['OFFENSE_NAME']) 
dataframe['victims_encoded'] = label_encoder.fit_transform(dataframe['VICTIM_TYPES'])
dataframe['race_encoded']= label_encoder.fit_transform(dataframe['OFFENDER_RACE']) 
dataframe.head(10)

OFFENDER_RACE  \
0                      White   
1  Black or African American   
2  Black or African American   
3  Black or African American   
4  Black or African American   
5  Black or African American   
6  Black or African American   
7  Black or African American   
8  Black or African American   
9  Black or African American   

                                        OFFENSE_NAME  \
0                                       Intimidation   
1                                     Simple Assault   
2                                 Aggravated Assault   
3  Aggravated Assault;Destruction/Damage/Vandalis...   
4                                 Aggravated Assault   
5                                            Robbery   
6                                 Aggravated Assault   
7  Aggravated Assault;Murder and Nonnegligent Man...   
8                                       Intimidation   
9                                            Robbery   

                        BIAS_DESC VICTIM_TYPES  offense_encoded  \
0  Anti-Black or African American   Individual              249   
1                      Anti-White   Individual              316   
2  Anti-Black or African American   Individual                0   
3                      Anti-White   Individual               21   
4                      Anti-White   Individual                0   
5                      Anti-White   Individual              303   
6                      Anti-White   Individual                0   
7                      Anti-White   Individual               58   
8                      Anti-White   Individual              249   
9                      Anti-White   Individual              303   

   victims_encoded  race_encoded  
0               34             6  
1               34             2  
2               34             2  
3               34             2  
4               34             2  
5               34             2  
6               34             2  
7               34             2  
8               34             2  
9               34             2

In [7]:
#Before we instantiate our ML model, we divide the dataset into two smaller training and testing datasets.
#We also set up our Features (X) and Labels (y) where X is 'offense_encoded','victims_encoded','race_encoded'.
#y is 'BIAS_DESC'

from sklearn.model_selection import train_test_split

# test size represents the proportion of training and testing data split. 
X = dataframe[['offense_encoded','victims_encoded','race_encoded']]
y = dataframe['BIAS_DESC']

#Random_state is set to 1 to define the "randomness" of data randomisation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
# Import  MultinomialNB from sklearn
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


# Create an instance of the model
nb_model = MultinomialNB()

# Fit model to training data
nb_model.fit(X_train, y_train)

MultinomialNB()

In [9]:
# Predict answers to data from the X_text dataset and show results in a confusion matrix
nb_model_predictions = nb_model.predict(X_test)

print(metrics.confusion_matrix(y_test,nb_model_predictions))

[[   0    0    0 ...    0    0   56]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0   41]
 [   0    0    0 ...    0    0 1955]]


In [10]:
#printing the classification report and the accuracy
print(metrics.classification_report(y_test,nb_model_predictions))

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                                                      precision    recall  f1-score   support

                                                               Anti-American Indian or Alaska Native       0.00      0.00      0.00       418
                                                    Anti-American Indian or Alaska Native;Anti-Asian       0.00      0.00      0.00         1
                                Anti-American Indian or Alaska Native;Anti-Black or African American       0.00      0.00      0.00         1
                                                                                           Anti-Arab       0.00      0.00      0.00       224
                                                            Anti-Arab;Anti-Black or African American       0.00      0.00      0.00         1
                                      Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)       0.00      0.00      0.00         1
     

In [11]:
print(metrics.accuracy_score(y_test,nb_model_predictions))

0.33040391251458506


In [12]:
# Import RandomForestClassifier from sklearn
from sklearn.ensemble import RandomForestClassifier

# An instance of the RF model is created
RF_model = RandomForestClassifier()

# Fitting the model to the training data
RF_model.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
# Predict answers to data from the X_text dataset
RF_model_predictions = RF_model.predict(X_test)

# Printing the confusion matrix
print(metrics.confusion_matrix(y_test,RF_model_predictions))

[[   3    0    0 ...    0    0  164]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    6]
 [   0    0    0 ...    0    0   47]
 [   8    0    0 ...    1    1 2920]]


In [14]:
#Printing classification report
print(metrics.classification_report(y_test,RF_model_predictions))

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                                                      precision    recall  f1-score   support

                                                               Anti-American Indian or Alaska Native       0.13      0.01      0.01       418
                                                    Anti-American Indian or Alaska Native;Anti-Asian       0.00      0.00      0.00         1
                                Anti-American Indian or Alaska Native;Anti-Black or African American       0.00      0.00      0.00         1
                                                                                           Anti-Arab       0.00      0.00      0.00       224
                                                            Anti-Arab;Anti-Black or African American       0.00      0.00      0.00         1
                                      Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)       0.00      0.00      0.00         1
     

In [15]:
#Printing the overall accuracy
print(metrics.accuracy_score(y_test,RF_model_predictions))

0.42134008589657657


In [16]:
# Import a Support Vector Classification model (SVC)
from sklearn.svm import SVC

# The gamma value is set to "auto" to avoid returning error. We fit the SVC model on our data. The confusion matrix is printed.

svc_model = SVC(gamma="auto")
svc_model.fit(X_train, y_train)

svc_model_predictions = svc_model.predict(X_test)

print(metrics.confusion_matrix(y_test, svc_model_predictions))

[[   2    0    0 ...    0    0  165]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    6]
 [   0    0    0 ...    0    0   48]
 [   4    0    0 ...    0    1 2944]]


In [17]:
# Importing a Support Vector Classification model (SVC)
print(metrics.classification_report(y_test,svc_model_predictions))

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                                                      precision    recall  f1-score   support

                                                               Anti-American Indian or Alaska Native       0.20      0.00      0.01       418
                                                    Anti-American Indian or Alaska Native;Anti-Asian       0.00      0.00      0.00         1
                                Anti-American Indian or Alaska Native;Anti-Black or African American       0.00      0.00      0.00         1
                                                                                           Anti-Arab       0.00      0.00      0.00       224
                                                            Anti-Arab;Anti-Black or African American       0.00      0.00      0.00         1
                                      Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)       0.00      0.00      0.00         1
     

In [18]:
#Printing the classification report and accuracy

print(metrics.accuracy_score(y_test,svc_model_predictions))

0.42193590030038974


In [19]:
#import LogisticRegression from sklearn
from sklearn.linear_model import LogisticRegression
#We build the model with the L-BFGS option.
#Once the model is built, the training data is then provided to the model.

logreg_model = LogisticRegression(solver = "lbfgs")

logreg_model.fit(X_train, y_train)

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [20]:
#We test the accuracy of the model using the test data.
#We import the sklearn.metrics module which includes score functions, performance metrics and pairwise metrics and distance computations. 
#We create a predictions set with some test data. This is unseen data

from  sklearn import metrics

# Creating a prediction set here
# Unseen contents of X_test
# The answers in y_test are expected which is a list of expected topic descriptions
logreg_model_predictions = logreg_model.predict(X_test)

In [21]:
# This is the predicted output from the model
logreg_model_predictions

array(['Anti-Black or African American', 'Anti-Black or African American',
       'Anti-Black or African American', ...,
       'Anti-Black or African American', 'Anti-Black or African American',
       'Anti-Black or African American'], dtype=object)

In [22]:
# Now we compare what the model predicted 
# with what is expected as output
# Printing a confusion matrix
print(metrics.confusion_matrix(y_test,logreg_model_predictions))

[[   0    0    0 ...    0    0   27]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0   25]
 [   0    0    0 ...    0    0 1251]]


In [23]:
# Printing a classification report
print(metrics.classification_report(y_test,logreg_model_predictions))

C:\Users\suchi\Anaconda3\envs\AI2_course\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                                                      precision    recall  f1-score   support

                                                               Anti-American Indian or Alaska Native       0.00      0.00      0.00       418
                                                    Anti-American Indian or Alaska Native;Anti-Asian       0.00      0.00      0.00         1
                                Anti-American Indian or Alaska Native;Anti-Black or African American       0.00      0.00      0.00         1
                                                                                           Anti-Arab       0.00      0.00      0.00       224
                                                            Anti-Arab;Anti-Black or African American       0.00      0.00      0.00         1
                                      Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)       0.00      0.00      0.00         1
     

In [24]:
# Printing the overall accuracy
print(metrics.accuracy_score(y_test,logreg_model_predictions))

0.36357091432685384


Reference:
    Dr. James Connolly's Semi-supervised learning practical notes from AI2.